"""empty message

Revision ID: 525bbe02b2ca
Revises: 3eb612f56ba1
Create Date: 2015-04-11 19:35:35.063595

"""

# revision identifiers, used by Alembic.
revision = '525bbe02b2ca'
down_revision = '3eb612f56ba1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_confirmation',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('hash_c', sa.String(), nullable=False),
                    sa.Column('activation_time', sa.DateTime(), nullable=True),
                    sa.Column('requested_time', sa.DateTime(), nullable=True),
                    sa.Column('expiration_date', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_confirmation')
    ### end Alembic commands ###
